ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "cartaoCnpjUrl" TEXT;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "verificationStatus" TEXT NOT NULL DEFAULT 'PENDING';
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "verifiedAt" TIMESTAMP(3);
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "rejectionReason" TEXT;
